DROP DATABASE IF EXISTS MOVIESDB;
CREATE DATABASE MOVIESDB;

GO
USE MOVIESDB;

CREATE TABLE MOVIE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (NEWID()),
    TITLE VARCHAR(255) UNIQUE NOT NULL,
    YEAR INT NOT NULL,
    DIRECTOR VARCHAR (255) NOT NULL,
    DURATION INT NOT NULL,
    POSTER VARCHAR,
    RATE DECIMAL(3,1) NOT NULL CONSTRAINT CK_MOVIES_RATE CHECK (RATE >= 0 AND RATE <= 10.0),
);

CREATE TABLE GENRE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE MOVIE_GENRES (
    MOVIE_ID UNIQUEIDENTIFIER,
    GENRE_ID INT,
    PRIMARY KEY(MOVIE_ID, GENRE_ID),

    CONSTRAINT FK_MOVIEGENRES_MOVIE FOREIGN KEY (MOVIE_ID)
        REFERENCES MOVIE(ID) ON DELETE CASCADE,
    
    CONSTRAINT FK_MOVIEGENRES_GENRE FOREIGN KEY (GENRE_ID)
        REFERENCES GENRE(ID) 
);

INSERT INTO GENRE (NAME) VALUES
('Drama'), ('Action'), ('Crime'), ('Adventure'), ('Sci-Fi'), ('Romance');