CREATE OR ALTER PROCEDURE UPDATE_MOVIE_GENRES
    @MOVIE_ID UNIQUEIDENTIFIER,
    @GENRES VARCHAR(MAX)
AS
BEGIN
    
    DECLARE @GENRELIST TABLE (VAL VARCHAR(100));

    INSERT INTO @GENRELIST (VAL)
    SELECT VALUE FROM STRING_SPLIT(@GENRES, ',')
    
    INSERT INTO MOVIE_GENRES (MOVIE_ID, GENRE_ID)
    SELECT @MOVIE_ID, G.ID
    FROM GENRE G
    INNER JOIN @GENRELIST GL
    ON G.NAME = GL.VAL
    WHERE NOT EXISTS(
        SELECT 1 
        FROM MOVIE_GENRES MG 
        WHERE MG.MOVIE_ID = @MOVIE_ID AND MG.GENRE_ID = G.ID  
    );

    --DELETE MISSING GENRES IN GENRELIST
    DELETE FROM MOVIE_GENRES
    WHERE MOVIE_ID = @MOVIE_ID
    AND GENRE_ID NOT IN(
        SELECT ID 
        FROM GENRE G 
        INNER JOIN @GENRELIST GL
        ON G.NAME = GL.VAL
    );

END