CREATE VIEW VW_MOVIES_WITH_GENRES AS
SELECT M.ID, M.TITLE, M.YEAR, M.DIRECTOR, M.DURATION, M.POSTER, M.RATE, STRING_AGG(G.NAME, ', ') AS GENRES
from MOVIE M INNER JOIN MOVIE_GENRES MG
ON M.ID = MG.MOVIE_ID
INNER JOIN GENRE G 
ON G.ID = MG.GENRE_ID
GROUP BY M.ID, M.TITLE, M.YEAR, M.DIRECTOR, M.DURATION, M.POSTER, M.RATE;